parameters:
#    golden_cage_fos_user.example.class: GoldenCage\FOSUserBundle\Example

services:
#    golden_cage_fos_user.example:
#        class: %golden_cage_fos_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
